version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    groups:
      python-dev:
        dependency-type: "development"
        patterns:
          - "*"
      python-prod:
        dependency-type: "production"
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    commit-message:
      prefix: "docker"
